name: Test code, update coverage, and release main branch

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [ ]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up SBT
        if: github.ref == 'refs/heads/main'
        uses: sbt/setup-sbt@v1.1.16
        with:
          sbt-runner-version: 1.10.11
      - name: Build and release
        if: github.ref == 'refs/heads/main'
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONA_USER: ${{ secrets.SONATYPE_USERNAME }}
          SONA_PASS: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_KEY_HEX: ${{ secrets.PGP_KEY_HEX }}
          CI: github
        run: |
          git fetch --prune --unshallow --tags &&
          export GPG_TTY=$(tty) &&
          echo $PGP_SECRET | base64 -d | gpg --passphrase=$PGP_PASSPHRASE --yes --batch --pinentry-mode loopback --import &&
          export PATH=`pwd`/.github/bin:$PATH &&
          sbt cogen/ciReleaseTagNextVersion cogen/ciReleaseSonatype
